imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $module: '@oksydan.is_searchbar.module'
      $context: '@oksydan.is_searchbar.context'

  Oksydan\IsSearchbar\:
    public: false;
    resource: '../../src/*'
    exclude:
      - '../../src/{Form,Controller,Search,Configuration,View}'
      - '../../src/index.php'
      - '../../src/*/index.php'

  Oksydan\IsSearchbar\Hook\:
    public: true
    resource: '../../src/Hook/*'
    exclude:
      - '../../src/*/index.php'

  Oksydan\IsSearchbar\Configuration\:
    public: true
    resource: '../../src/Configuration/*'
    exclude:
      - '../../src/*/index.php'

  Oksydan\IsSearchbar\View\:
    public: true
    resource: '../../src/View/*'
    exclude:
      - '../../src/*/index.php'

  Oksydan\IsSearchbar\Search\:
    public: true
    resource: '../../src/Search/*'
    exclude:
      - '../../src/Search/Collection/ProductCollection.php'
      - '../../src/Search/DTO/*'
      - '../../src/Search/index.php'
      - '../../src/Search/*/index.php'
