services:

  oksydan.is_searchbar.module:
    class: Is_searchbar
    factory: [ 'Module', 'getInstanceByName' ]
    public: false
    arguments:
      - 'is_searchbar'

  oksydan.is_searchbar.context:
    class: Context
    factory: [ '\Context', getContext ]

